spring:
  datasource:
    url: jdbc:mysql://localhost:3308/test_db?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

jwt:
  signerKey: "test-sign-key"
  valid-duration: 3600
  refreshable-duration: 1800
